action test

diff --git a/.github/workflows/astro-deploy.yml b/.github/workflows/astro-deploy.yml
--- a/.github/workflows/astro-deploy.yml
+++ b/.github/workflows/astro-deploy.yml
@@ -1,42 +1,93 @@
-name: Github Pages Astro CI
+# Sample workflow for building and deploying a astro site to GitHub Pages
+#
+#
+name: Deploy astro site to Pages
 
 on:
-  # Trigger the workflow every time you push to the `main` branch
-  # Using a different branch name? Replace `main` with your branch’s name
+  # Runs on pushes targeting the default branch
   push:
-    branches: [main]
-  # Allows you to run this workflow manually from the Actions tab on GitHub.
+    branches: [$default-branch]
+
+  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
+
+# Default to bash
+defaults:
+  run:
+    shell: bash
+
 jobs:
-  deploy:
-    runs-on: ubuntu-20.04
-
-    # Allow this job to push changes to your repository
-    permissions:
-      contents: write
-
+  # Build job
+  build:
+    runs-on: ubuntu-latest
     steps:
-      - name: Check out your repository using git
-        uses: actions/checkout@v2
-
-      - name: Use Node.js 16
-        uses: actions/setup-node@v2
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
         with:
-          node-version: 16
-
-      # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        id: pages
+        uses: actions/configure-pages@v1
+        with:
+          # Automatically inject pathPrefix in your astro configuration file.
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: astro
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            public
+            .cache
+          key: ${{ runner.os }}-astro-build-${{ hashFiles('public') }}
+          restore-keys: |
+            ${{ runner.os }}-astro-build-
       - name: Install dependencies
         run: npm ci
-
-      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
-      - name: Build Astro
+      - name: Build with astro
         run: npm run build
-
-      - name: Deploy to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          # `./dist` is the default Astro build directory.
-          # If you changed that, update it here too.
-          publish_dir: ./dist
+          path: ./public
+
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
